### PR TITLE
update lua scripts

### PR DESCRIPTION
**Pull request by cwen0**
1. use the newest sysbench lua scripts.

### CODE REVIEW

**Comment by siddontang** [comment]
Please add a PR description. I guess you here just want to update the newest sysbench?

**Comment by cwen0** [comment]
yes, I just want to update the newest lua scripts. The newest lua scripts use ` prepared statement`. `prepared statement `  is good for tidb.

**Comment by coocood** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
