### PR TITLE
add star schema benchmark

### PR DESCRIPTION
**Pull request by zz-jason**
1. There are 5 tables in the Star Schema Benchmark, table schemas are defined in [create_table.sql](https://github.com/pingcap/tidb-bench/blob/zz-jason/ssb/ssb/create_table.sql), I wrote them one by one according to [the paper](https://www.cs.umb.edu/~poneil/StarSchemaB.PDF), please check them carefully.
2. There are 13 queries in the Star Schema Benchmark, listed in directory [queries](https://github.com/pingcap/tidb-bench/tree/zz-jason/ssb/ssb/queries), I pasted them from [the same paper](https://www.cs.umb.edu/~poneil/StarSchemaB.PDF)
3. [dbgen](https://github.com/pingcap/tidb-bench/tree/zz-jason/ssb/ssb/dbgen) is taken from [electrum/ssb-dbgen](https://github.com/electrum/ssb-dbgen), with the following modifications:
    - fix build on linux, see https://github.com/electrum/ssb-dbgen/pull/1
    - fix some typo, see https://github.com/electrum/ssb-dbgen/pull/7
    - fix some compile warnings

@zimulala @shenli PTAL

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by winoros** [comment]
Any current benchmark result?

**Comment by zz-jason** [comment]
@winoros No, you can have a try.

**Comment by shenli** [comment]
LGTM
We could add this to the bench_bot.

**Comment by zz-jason** [comment]
I have made a simply test on these 13 queries with scale factor 1, all of them are executed within 3s. Their test scenario seems simpler than TPC-H

**Pull request merged**
